server:
  port: 8080
spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ape-frame?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 1234
#    lettuce:     #连接池设置,还有个jedis    用这个池要引入apache的commons-pool2
#      pool:
#        max-active: 20
#        max-idle: 8
#        max-wait: -1
#        min-idle: 0
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: -1
        min-idle: 0

init:
  cache:
    reload: true



sql:
  beauty:
    show: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete_flag       #逻辑删除字段（不是物理删除） 要在实体类的字段加上TableLogic注解
      logic-delete-value: 1
      logic-not-delete-value: 0
swagger:
  base-package: com.lojc
  contact-name: Lojc
  email: lojc719@gmail.com
  contact-url: https://github.com/Lojc6
  description: Test
  title: Controller Management
  version: 1.0

